### PR TITLE
Change Poison -> Jason for JSON parser and generator

### PR DESCRIPTION
**Pull request by indocomsoft**
For performance reasons: quoting its README:
> The parser and generator are at least twice as fast as other Elixir/Erlang libraries (most notably `Poison`). The performance is comparable to `jiffy`, which is implemented in C as a NIF. Jason is usually only twice as slow.

### CODE REVIEW

**Comment by tuesmiddt** [comment]
Can you regenerate the lockfile as well?

**Comment by indocomsoft** [comment]
Eh, I don't think I need to since `jason` is already a dependency of `excoveralls`

**Comment by indocomsoft** [comment]
In any case, I recreated `mix.lock` and there's an update to `meck` apparently

**Comment by tuesmiddt** [comment]
Ah I was thinking poison could be removed from the lockfile but I think something else depends on it. 

In any case, `Poison` is still being used in the following test files: 
- assessments_test
- question_test
- mcq_question_test
- programming_question_test

Do you want to change them as well?

**Comment by indocomsoft** [comment]
@tuesmiddt actually there's #122 (removing json deserialisers) which would remove some changes from here, so I think you should look at that PR first before this one.

**Pull request merged**
