### PR TITLE
Do not clone if CS1101S is already cloned

### LINKED ISSUE #197: Error message shows up on start-up if CS1101S repo is already cloned
According to the log:
image

### PR DESCRIPTION
**Pull request by indocomsoft**
Fixes #197

### CODE REVIEW

**Comment by indocomsoft** [comment]
@ningyuansg 
```bash
502 $ git clone git@bitbucket.org:cs1101s/cs1101s.git
Cloning into 'cs1101s'...
remote: Counting objects: 17354, done.
remote: Compressing objects: 100% (278/278), done.
remote: Total 17354 (delta 61), reused 0 (delta 0)
Receiving objects: 100% (17354/17354), 252.93 MiB | 926.00 KiB/s, done.
Resolving deltas: 100% (2557/2557), done.
Checking out files: 100% (2887/2887), done.
```
I did a test just now. During the `Receiving objects` step, the directory content is:
```bash
.
./.git
./.git/config
./.git/objects
./.git/objects/pack
./.git/objects/pack/tmp_pack_DnUuwa
./.git/objects/pack/tmp_pack_LDbz68
./.git/objects/info
./.git/HEAD
./.git/info
./.git/info/exclude
./.git/description
./.git/hooks
./.git/hooks/commit-msg.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/pre-commit.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-receive.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/pre-push.sample
./.git/hooks/update.sample
./.git/refs
./.git/refs/heads
./.git/refs/tags
./.git/FETCH_HEAD
```

Only at the `Resolving deltas` step does `index.lock` is created.
```bash
.
./.gitignore
[REDACTED]
./.git
./.git/index.lock
./.git/config
./.git/objects
./.git/objects/pack
./.git/objects/pack/pack-5b0b6cf27207b72cb4ceb01f58fd525491e343bf.idx
./.git/objects/pack/pack-5b0b6cf27207b72cb4ceb01f58fd525491e343bf.pack
./.git/objects/pack/tmp_pack_DnUuwa
./.git/objects/info
./.git/HEAD
./.git/info
./.git/info/exclude
./.git/logs
./.git/logs/HEAD
./.git/logs/refs
./.git/logs/refs/heads
./.git/logs/refs/heads/master
./.git/logs/refs/remotes
./.git/logs/refs/remotes/origin
./.git/logs/refs/remotes/origin/HEAD
./.git/description
./.git/hooks
./.git/hooks/commit-msg.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/pre-commit.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-receive.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/pre-push.sample
./.git/hooks/update.sample
./.git/refs
./.git/refs/heads
./.git/refs/heads/master
./.git/refs/tags
./.git/refs/remotes
./.git/refs/remotes/origin
./.git/refs/remotes/origin/HEAD
./.git/packed-refs
./.git/FETCH_HEAD
```

So it still does not fully solve the problem

**Comment by indocomsoft** [comment]
One possible solution that I can think of is to create a lockfile ourselves to track whether the repo is being cloned. If we decide upon this path, then you should include in the deployment book that they might need to remove manually this lockfile if the process is abruptly killed.

@tuesmiddt any ideas?

**Comment by ningyuansg** [comment]
How about a `ps aux | grep git`

**Comment by indocomsoft** [comment]
so we're assuming no other git would run? I guess that'd work although it feels like a hack

**Comment by indocomsoft** [comment]
@ningyuansg Can you check whether the EC2 instance has `pgrep` installed? If it is, then running `pgrep git` is much better since `ps aux | grep git` would at least return `grep git`

**Comment by ningyuansg** [comment]
`pgrep` is installed, but the lockfile does sound cleaner. Worth noting that this issue is not fatal, though. Can always move this to a github issue.

**Comment by indocomsoft** [comment]
Yeah, I think we shld deal with this in a separate issue. Created #199

**Comment by indocomsoft** [comment]
@ningyuansg maybe you can approve this PR then?

**Comment by tuesmiddt** [comment]
@ningyuansg I think it won't be a problem since `git clone` has been changed to run every midnight instead of every minute in #159

**Comment by ningyuansg** [comment]
Yea, sorry for the tangent.

**Pull request merged**
