### PR TITLE
Generate empty submissions for contests too

### PR DESCRIPTION
**Pull request by angelsl**

### CODE REVIEW

**Comment by jiachen247** [comment]
@angelsl I think you broke a test!

**Comment by jiachen247** [comment]
Resolves #518

**Comment by angelsl** [comment]
Fixed!

**Comment by jiachen247** [comment]
After much discussion, I think there is a cleaner way to solve the problem at hand + there a few side effect of removing this clause that I rather not deal with! Closing this PR for now. Do let me know if yall have any issues! Thanks anyways for the work @angelsl and @Aulud :-)

**Pull request closed without merging**
