### PR TITLE
Encrypt RDS password with KMS, add Lambda to terraform

### LINKED ISSUE #15: Terraform ECS task or Lambda Function for Running Student Submission
Try Lambda first, if it doesn't work use ECS

### LINKED ISSUE #95: Resolve security issue of terraform deployment
According to @evansb's comments on #81

### PR DESCRIPTION
**Pull request by ningyuansg**
### Features

- Resolves #15 
- Resolves #95

### CODE REVIEW

**Comment by ningyuansg** [comment]
@indocomsoft I think you didn't add the review comment that has the question

**Comment by indocomsoft** [comment]
Oh, basically for the `Mix.env()`, during compilation for production, it should be `:prod` right? Cos I've never compiled for production before.

**Comment by ningyuansg** [comment]
Yep, it's `:prod`. Staging servers are actually running off this branch right now.

**Comment by indocomsoft** [comment]
Alright, cool.

**Pull request merged**
